### ISSUE TITLE
Error in the readme

### ISSUE THREAD

**Issue by deltastateonline** [byjg/micro-orm#8]
Hi,
Could you please verify that this code snippet in the read me is correct
`$dataset = new ByJG\AnyDataset\Db\Factory('mysql://user:password@server/schema');

$repository = new \ByJG\MicroOrm\Repository($dataset, $mapper);`

or should it be something like
`$dataset = ByJG\AnyDataset\Db\Factory::getDbRelationalInstance('sqlite:db/test.db');

$repository = new \ByJG\MicroOrm\Repository($dataset, $mapper);`

**Comment by byjg** [comment]
The second code snippet is correct:

```
$dataset = ByJG\AnyDataset\Db\Factory::getDbRelationalInstance('sqlite:db/test.db');
$repository = new \ByJG\MicroOrm\Repository($dataset, $mapper);
```

However the second URI is not correct. Below the correct ones:
- mysql://user:password@server/schema
- sqlite:///tmp/db/test.db

You always need to use `//` to divide the `schema` and when you not have the `host` part, the path should be absolute.

**Comment by deltastateonline** [comment]
thanks for the correction,
I have had a look at the readme file in the distribution installed from composer, it contains more details

**Comment by byjg** [comment]
If you want you can access the documentation of all componentes here:

http://opensource.byjg.com/

And direct links for the componentes that Micro Orm uses:
https://opensource.byjg.com/micro-orm
https://opensource.byjg.com/anydataset/
https://opensource.byjg.com/anydataset-db/
https://opensource.byjg.com/uri/
https://opensource.byjg.com/serializer/

**Comment by deltastateonline** [comment]
Thanks for fixing the readme. Awesome library.

**Comment by byjg** [comment]
You're welcome
