### ISSUE TITLE
snake case field name

### ISSUE THREAD

**Issue by deltastateonline** [byjg/micro-orm#9]
Good day,
Is it possible to have a field name with an under score? Currently have to integrate with a application which has a few fields with under scores in their field names.

**Comment by byjg** [comment]
Sure, it is possible. The Micro Orm relies on the DTO class in order to get/put data on database. You can create a map with underscore like this:

```
class MyTable 
{
    public $field_id;
    public $field_value;
}
``` 

*or* you can create a FieldMap like this:

```
// The class does not have the snake case
class MyTable
{
    protected $fieldid;
    protected $fieldvalue;

    public function getFieldId() {...}
    public function setFieldId($field_id) {...}
    public function getFieldValue() {...}
    public function setFieldValue($field_value) {...}
}

// Creating the mapping
$mapper = new \ByJG\MicroOrm\Mapper(
    \ByJG\Sample\MicroOrm\SnakeCase\MyTable::class,
    'my_table',
    'field_id'
);

// Here we are mapping the DTO property to a database field property
$mapper->addFieldMap("fieldid", "field_id");
$mapper->addFieldMap("fieldvalue", "field_value");
``` 

A created a Gist with a full functional example. I hope it help you.

**Comment by byjg** [comment]
Here the gist: https://gist.github.com/byjg/ba6dbfbe3424ad5da1471bd545e82598

**Comment by deltastateonline** [comment]
thanks for the update, I was using the add field alias instead. But I think that is for select joins

**Comment by byjg** [comment]
Yes, you're correct - Field Alias is for select joins :)
